setup:
  resources_dir: /gpfs/home/yb2612/yb2612_tsirigos/Chromnitron/data/chromnitron/input_resources  # (Required) Path to input resources
  inputs_dir: /gpfs/home/yb2612/yb2612_tsirigos/Chromnitron/data/twins_multiome/muon_twins/inputs  # (Required) Path to input data directories, must exist
  sample_sheet: samplesheet.csv  # (Required) Name of CSV file in inputs_dir with columns: sampleName, path (to 10x multiome folder), (optional) SoupOrCellDF
  mudata_file: /gpfs/home/yb2612/yb2612_tsirigos/Chromnitron/data/twins_multiome/muon_twins/outputs/objects/Pool1_by_donor_postqc.h5mu  # (Optional) Path to existing MuData file to use as input instead of creating new one
  base_project_dir: /gpfs/home/yb2612/yb2612_tsirigos/Chromnitron/data/twins_multiome/muon_twins  # Base directory for project outputs, will be created if does not exist
  project_prefix: Pool1  # Prefix for naming files
  
# Define the steps of the pipeline to run, in order (comment out steps to skip)
steps_to_run:  
  # - create_data_dirs
  # - create_mudata
  # - add_donor_metadata
  # - call_peaks
  # - qc
  # - filter
  # - postqc
  - cluster
  # - link_peaks_to_genes
  # - footprint
  # - differential_analysis

# Below are step-specific configurations

call_peaks_config:
  macs2_path:  # Path to MACS2 environment
  grouping_var:  # Grouping variable for peak calling algorithm

qc_config:
  qc_sheet_path:  # (Optional) Path to CSV file containing clusters to remove per sample
  grouping_var: donor # Grouping variable for QC summary and plots
  plotting: True  # Whether to generate QC plots

filter_config:
  filter_all_modalities: True  # Whether to filter both RNA and ATAC modalities based on QC metrics
  rna:
    min_n_genes_by_counts: 500
    min_total_counts: 1000
    max_total_counts: 25000
    max_percent_mt: 20.0
  atac:
    min_n_genes_by_counts: 500
    min_total_counts: 5000
    max_total_counts: 70000
    max_nucleosome_signal: 2.0
    min_tss_score: 1.0
  grouping_var: donor  # Grouping variable for QC summary and plots
  plotting: True  # Whether to generate QC plots after filtering

postqc_config:
  run_harmony: True  # Whether to run Harmony batch correction after QC
  grouping_var: donor  # Grouping variable for post-QC summary and plots
  plotting: True  # Whether to generate post-QC plots

cluster_config:
  params:
    n_neighbors: 10  # Number of neighbors for clustering
    min_dist: 0.5  # Minimum distance for UMAP
    resolution: 0.5  # Resolution for clustering
    random_state: 9  # Random state for reproducibility
  grouping_var: rna_leiden  # Grouping variable for cluster plots
  plotting: True  # Whether to generate cluster plots


footprint_config:
  footprint_peaks_path:  # Path to TXT file containing ATAC peaks to run footprinting on




