setup:
  project_prefix: Pool1  # Prefix for naming files
  resources_dir: /gpfs/home/yb2612/yb2612_tsirigos/Chromnitron/data/chromnitron/input_resources  # (Required) Path to input resources
  inputs_dir: /gpfs/home/yb2612/yb2612_tsirigos/Chromnitron/data/twins_multiome/muon_twins/inputs  # (Required) Path to input data directories, must exist
  sample_sheet: samplesheet.csv  # (Required) Name of CSV file in inputs_dir with columns: sampleName, path (to 10x multiome folder), (optional) SoupOrCellDF
  base_project_dir: /gpfs/home/yb2612/yb2612_tsirigos/Chromnitron/data/twins_multiome/muon_twins  # Base directory for project outputs, will be created if does not exist
  mudata_file: /gpfs/home/yb2612/yb2612_tsirigos/Chromnitron/data/twins_multiome/muon_twins/outputs/objects/Pool1.h5mu  # (Optional) Path to existing MuData file to use as input instead of creating new one
  metadata_file: /gpfs/home/yb2612/yb2612_tsirigos/Chromnitron/data/twins_multiome/muon_twins/inputs/metadata_romane_muon.csv  # (Optional) Path to CSV file with metadata to add to MuData object
  metadata_key: cell_type  # (Optional) Column name in metadata_file to use as key for merging metadata
  
# Define the steps of the pipeline to run, in order (comment out steps to skip)
steps_to_run:  
  # - initialize
  # - create_mudata
  # - add_donor_metadata
  # - call_peaks
  - qc
  - filter
  - postqc
  - cluster
  - add_metadata
  # - link_peaks_to_genes
  # - footprint
  # - differential_analysis

# Below are step-specific configurations

call_peaks_config:
  grouping_var:  # Grouping variable for peak calling algorithm

qc_config:
  qc_sheet_path:  # (Optional) Path to CSV file containing clusters to remove per sample
  plotting: True  # Whether to generate QC plots
  grouping_vars:  # Grouping variables for QC summary and plots
    - sample
    - donor

filter_config:
  filter_all_modalities: False  # Whether to filter both RNA and ATAC modalities based on QC metrics
  rna:
    min_n_genes_by_counts: 500
    min_total_counts: 1000
    max_total_counts: 25000
    max_percent_mt: 20.0
  atac:
    min_n_genes_by_counts: 500
    min_total_counts: 5000
    max_total_counts: 70000
    max_nucleosome_signal: 2.0
    min_tss_score: 1.0
  plotting: True  # Whether to generate QC plots after filtering
  grouping_vars:  # Grouping variables for QC summary and plots
    - sample
    - donor

postqc_config:
  run_harmony: True  # Whether to run Harmony batch correction after QC
  plotting: True  # Whether to generate post-QC plots
  grouping_vars:  # Grouping variables for post-QC plots
    - sample
    - donor

cluster_config:
  params:
    n_neighbors: 10  # Number of neighbors for clustering
    min_dist: 0.5  # Minimum distance for UMAP
    resolution: 0.5  # Resolution for clustering
    random_state: 9  # Random state for reproducibility
  plotting: True  # Whether to generate cluster plots
  grouping_vars:  # Grouping variables for UMAP plots
    - sample
    - donor
    - rna_leiden
    - atac_leiden
    - cell_type

footprint_config:
  footprint_peaks_path:  # Path to TXT file containing ATAC peaks to run footprinting on




