setup:
  inputs_dir: /gpfs/home/yb2612/yb2612_tsirigos/Chromnitron/data/PsO_multiome/muon_multiome_test  # Path to input data directory
  sample_sheet: samplesheet.csv  # Required: CSV file with columns: sampleName,path (path to 10x multiome data directory)
  mudata_files: # Optional: path to existing MuData file/s to start from
    - /gpfs/home/yb2612/yb2612_tsirigos/Chromnitron/data/PsO_multiome/muon_code/outputs/muon_multiome-Rep1-created.h5mu 
    - /gpfs/home/yb2612/yb2612_tsirigos/Chromnitron/data/PsO_multiome/muon_code/outputs/muon_multiome-Rep2-created.h5mu
  base_project_dir: /gpfs/home/yb2612/yb2612_tsirigos/Chromnitron/data/PsO_multiome/muon_multiome_test  # Base directory for outputs
  project_prefix: muon_twins  # Prefix for project files

steps_to_run:  # Define the steps of the pipeline to run, in order (comment out steps to skip)
  - create_data_dirs
  - create_mudata
  - peak_calling
  - qc
  # - postqc
  # - clustering
  # - merge
  # - link_peaks_to_genes
  # - footprinting

peak_calling_config:
  macs2_path:  # Path to MACS2 environment
  grouping_var:  # Grouping variable for peak calling algorithm

qc_config:
  gff_path: /gpfs/home/yb2612/yb2612_tsirigos/Chromnitron/Chromnitron_differential/input_data/input_resources/DNA_sequence/gencode.v45.transcripts.annotation.gff3  # Path to GFF3 annotation file to convert to BED, or empty to use default
  features_bed_path: /gpfs/home/yb2612/yb2612_tsirigos/Chromnitron/Chromnitron_differential/input_data/input_resources/DNA_sequence/gencode.v45.annotation.features.bed  # Path to BED file with genomic features, or empty to use default
  qc_sheet_path:  # Optional: Path to CSV file containing clusters to remove per sample
  split_by_sample: False  # Whether to split QC metrics by sample
  plotting: True  # Whether to generate QC plots

postqc_config:
  run_harmony: True  # Whether to run Harmony batch correction after QC

filtering_config:
  max_mito_frac: 0.2  # Maximum mitochondrial fraction for filtering
  min_genes: 200  # Minimum number of genes for filtering
  max_genes: 6000  # Maximum number of genes for filtering
  min_counts: 500  # Minimum number of counts for filtering
  max_counts: 50000  # Maximum number of counts for filtering
  min_peaks: 1000  # Minimum number of ATAC peaks for filtering
  max_peaks: 50000  # Maximum number of ATAC peaks for filtering
  
footprinting_config:
  footprint_peaks_path:  # Path to TXT file containing ATAC peaks to run footprinting on
    
output:
  outdir: outputs
  





